kind: pipeline
type: docker
name: push-to-registry

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: bots-server:5000/free-bots/rss-bridge
      tags: latest
      registry: bots-server:5000
      force_tag: true
      insecure: true
    when:
      branch: botsFlavor
  - name: redeploy
    image: plugins/webhook
    settings:
      urls: http://bots-server:1150/redeploy
      content_type: application/json
      template: { "stack": "rss-bridge" }
    when:
      branch: botsFlavor
